GHA for apply-twice

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -17,8 +17,40 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
-  build:
+  build-make-me-impl:
     name: Build Make Me Impl
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install Rust
+        run: rustup update stable # Ensure Rust is installed and updated
+
+      - name: Build
+        run: cargo build --verbose
+
+      - name: Run tests
+        run: cargo test --verbose
+
+      - name: Check for test failures
+        run: |
+          if [ -n "$(cargo test --verbose 2>&1 | grep "thread 'main' panicked")" ]; then
+            echo "Tests failed"
+            exit 1
+          fi
+
+      - name: Check for formatting errors
+        run: cargo fmt -- --check
+
+      - name: Check for security vulnerabilities
+        run: cargo audit
+
+      - name: Check for outdated dependencies
+        run: cargo outdated
+
+  apply-twice:
+    name: Apply Twice
     runs-on: ubuntu-latest
 
     steps:
